# cleaner/structural.py
# Structural fixes: unmerge cells, drop duplicate/empty/footer/duplicate rows,
# and business-key deduplication.
# Part of Tessergrid - AI Data Cleaner

import os
import re
import pandas as pd
import openpyxl


# Uses openpyxl to unmerge all merged cell ranges, forward-filling the top-left
# value into every cell that was previously covered by the merge.
# Saves to a temp file, loads into pandas, then cleans up the temp file.
def unmerge_and_load(filepath):
    wb = openpyxl.load_workbook(filepath)
    ws = wb.active
    unmerged_count = 0

    for merged_range in list(ws.merged_cells.ranges):
        min_row = merged_range.min_row
        min_col = merged_range.min_col
        max_row = merged_range.max_row
        max_col = merged_range.max_col
        top_left_value = ws.cell(min_row, min_col).value
        ws.unmerge_cells(str(merged_range))
        for row in range(min_row, max_row + 1):
            for col in range(min_col, max_col + 1):
                ws.cell(row, col).value = top_left_value
        unmerged_count += 1

    tmp_path = str(filepath).replace(".xlsx", "_tmp_unmerged.xlsx")
    wb.save(tmp_path)
    df = pd.read_excel(tmp_path, dtype=str, keep_default_na=False)
    os.remove(tmp_path)
    return df, unmerged_count


# Finds and removes duplicate column names (case-insensitive, ignoring extra whitespace).
# Keeps the first occurrence and drops subsequent duplicates.
# Returns the cleaned DataFrame and a list of fix log entries.
def fix_duplicate_columns(df):
    fix_log = []
    headers = list(df.columns)
    normalized = [re.sub(r"\s+", " ", h.strip().lower()) for h in headers]
    seen = {}
    cols_to_drop = []
    for idx, norm in enumerate(normalized):
        if norm in seen:
            cols_to_drop.append(headers[idx])
            fix_log.append({
                "fix_type": "duplicate_columns",
                "column": headers[idx],
                "original": headers[idx],
                "fixed": f"Removed (duplicate of '{headers[seen[norm]]}')",
                "action": f"Dropped duplicate column '{headers[idx]}' — same as column '{headers[seen[norm]]}'"
            })
        else:
            seen[norm] = idx
    df = df.drop(columns=cols_to_drop)
    return df, fix_log


# Removes rows where every cell is empty or whitespace.
# Returns the cleaned DataFrame and fix log entries for each row removed.
def fix_empty_rows(df):
    fix_log = []
    empty_mask = df.apply(
        lambda row: all(str(v).strip() == "" for v in row), axis=1
    )
    empty_indices = df[empty_mask].index.tolist()
    for idx in empty_indices:
        excel_row = idx + 2
        fix_log.append({
            "fix_type": "empty_rows",
            "row": excel_row,
            "original": "(empty row)",
            "fixed": "Row removed",
            "action": f"Removed completely empty row {excel_row}"
        })
    df = df[~empty_mask].reset_index(drop=True)
    return df, fix_log


# Removes duplicate rows, keeping only the first occurrence.
# Excludes the Notes column from comparison since it may differ between duplicates.
# Returns the cleaned DataFrame and fix log entries.
def fix_duplicate_rows(df):
    fix_log = []
    cols_to_check = [c for c in df.columns if c.strip().lower() != "notes"]
    dup_mask = df.duplicated(subset=cols_to_check, keep="first")
    dup_indices = df[dup_mask].index.tolist()
    for idx in dup_indices:
        excel_row = idx + 2
        order_id = str(df.iloc[idx, 0]).strip()
        fix_log.append({
            "fix_type": "duplicate_rows",
            "row": excel_row,
            "original": f"Duplicate of row with Order ID: {order_id}",
            "fixed": "Row removed",
            "action": f"Removed duplicate row {excel_row} (Order ID: {order_id})"
        })
    df = df[~dup_mask].reset_index(drop=True)
    return df, fix_log


# Removes ERP footer rows — rows where the first column contains known footer
# patterns like "TOTAL SUMMARY", "GENERATED BY", etc. rather than real data.
# Returns the cleaned DataFrame and fix log entries.
def fix_erp_footer_rows(df):
    FOOTER_PATTERNS = [
        r"total\s+summary",
        r"generated\s+by",
        r"grand\s+total",
        r"report\s+date",
        r"printed\s+by",
    ]
    fix_log = []
    combined_pattern = re.compile("|".join(FOOTER_PATTERNS), re.IGNORECASE)
    footer_mask = df.iloc[:, :3].apply(
        lambda row: any(combined_pattern.search(str(v)) for v in row), axis=1
    )
    for idx in df[footer_mask].index:
        val = str(df.iloc[idx, 0]).strip()
        fix_log.append({
            "fix_type": "erp_footer_rows",
            "row": idx + 2,
            "original": val,
            "fixed": "Row removed",
            "action": f"Removed ERP footer row: '{val}'"
        })
    df = df[~footer_mask].reset_index(drop=True)
    return df, fix_log


# Deduplicates rows using a business key after all normalization is complete.
# Key columns: order_id, sku, supplier, warehouse, order_date, qty_ordered, qty_shipped.
# Resolves case-insensitively — uses whatever column names match these keywords.
# Keeps first occurrence; removes subsequent duplicates.
# Returns the deduplicated DataFrame and fix log entries.
def fix_duplicate_by_business_key(df):
    fix_log = []

    # Business key column keyword patterns (keyword → column name found in df)
    _KEY_PATTERNS = [
        ("order", "id"),
        ("sku",),
        ("supplier",),
        ("warehouse",),
        ("order", "date"),
        ("qty", "order"),
        ("qty", "ship"),
    ]

    def find_col(*keywords):
        for c in df.columns:
            cl = c.lower()
            if all(kw in cl for kw in keywords):
                return c
        return None

    key_cols = []
    for pattern in _KEY_PATTERNS:
        col = find_col(*pattern)
        if col and col not in key_cols:
            key_cols.append(col)

    if not key_cols:
        return df, fix_log

    dup_mask = df.duplicated(subset=key_cols, keep="first")

    order_col = find_col("order", "id")
    for idx in df[dup_mask].index:
        excel_row = idx + 2
        order_id  = str(df.at[idx, order_col]).strip() if order_col else "?"
        fix_log.append({
            "fix_type": "duplicate_rows",
            "row":      excel_row,
            "column":   order_col or key_cols[0],
            "original": f"Duplicate business key (Order ID: {order_id})",
            "fixed":    "Row removed",
            "action":   f"Removed post-normalization duplicate row {excel_row} (Order ID: {order_id})",
        })

    df = df[~dup_mask].reset_index(drop=True)
    return df, fix_log
